# -*- coding: utf-8 -*-
"""NLP TEXT CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJypZEApIpY5ij1DJchTa2kGgrShxsV7
"""

# ---- NLP Text Classification
import os, sys, subprocess, joblib
try:
    import sklearn, pandas, matplotlib, seaborn
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q",
                           "scikit-learn", "pandas", "matplotlib", "seaborn"])

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline

OUT = "nlp_project"
os.makedirs(OUT, exist_ok=True)  # idempotent

# 1) Load data (4 categories, headers/footers removed to avoid leakage)
CATS = ["sci.med", "sci.space", "rec.sport.hockey", "comp.graphics"]
try:
    train = fetch_20newsgroups(subset="train", categories=CATS,
                               remove=("headers", "footers", "quotes"))
    test = fetch_20newsgroups(subset="test", categories=CATS,
                              remove=("headers", "footers", "quotes"))
except Exception as e:
    raise SystemExit(f"Dataset download failed (check internet in Colab): {e}")

print(f"Train docs: {len(train.data)}, Test docs: {len(test.data)}")

# 2) NLP pipeline: text preprocessing + TF-IDF + Logistic Regression
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(lowercase=True, stop_words="english",
                              ngram_range=(1, 2), max_features=30000)),
    ("clf", LogisticRegression(max_iter=1000)),
])
pipe.fit(train.data, train.target)

# 3) Evaluate
pred = pipe.predict(test.data)
print("Accuracy:", round(accuracy_score(test.target, pred), 4))
print(classification_report(test.target, pred, target_names=train.target_names))

# 4) Confusion matrix plot
cm = confusion_matrix(test.target, pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=train.target_names, yticklabels=train.target_names)
plt.title("NLP Text Classifier - Confusion Matrix")
plt.tight_layout()
plt.savefig(f"{OUT}/confusion_matrix.png", dpi=150)
plt.show()

# 5) Save model + quick demo
joblib.dump(pipe, f"{OUT}/text_classifier.joblib")
samples = ["NASA launched a new satellite to orbit Mars",
           "The goalie made 30 saves in the playoff game"]
for s, p in zip(samples, pipe.predict(samples)):
    print(f"{s!r} -> {train.target_names[p]}")